"""remove decimal

Revision ID: 74e27a4366ed
Revises: 89ed1946942c
Create Date: 2020-12-13 18:02:52.217376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e27a4366ed'
down_revision = '89ed1946942c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
