"""Changed field name

Revision ID: ccb916a3163e
Revises: 26b13a97fe1f
Create Date: 2020-12-13 16:09:14.967365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccb916a3163e'
down_revision = '26b13a97fe1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=1000), nullable=True))
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
